title: Xinshuai Dong
url: "https://dongxinshuai.github.io"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
# - name: "Resume"
#   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
