title: Xinshuai Dong 董新帅
url: "https://dongxinshuai.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page"


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=A7JyL1sAAAAJ&hl=en"
# - name: "Resume"
#   link: "resume.pdf"
 - name: "GitHub"
   link: "https://github.com/dongxinshuai"
